### ISSUE TITLE
Exercise: Module 5, class 1 prep / Valgrind

### ISSUE THREAD

**Issue by newjoiner** [LaunchCodeEducation/cs50x-live#120]
@jesseilev There is a Todo for an exercise in the A few pitfalls with memory section below.  

https://github.com/LaunchCodeEducation/cs50x-live/tree/feature/module5/calendar/cs50/unit2-advanced-c/module5/materials/class1-prep#a-few-pitfalls-with-memory

You can update the calendar at the link above and put the exercise [here](https://github.com/LaunchCodeEducation/cs50x-live/tree/feature/module5/calendar/cs50/unit2-advanced-c/module5/materials/exercises)

The instructions for the exercise:

> TODO exc make em use valgrind to find a leak, and then fix the leak

**Comment by stlou** [comment]
For the Valgrind "Leaky" exercise, we're missing the leaky.c file @jesseilev
