### ISSUE TITLE
Final QA: Module 3

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/cs50x-live#139]
Check Module 3 for final problems we missed.

Then we're ready to publish!

**Comment by newjoiner** [comment]
@jesseilev I went over Module 3 and besides some some spelling errors, table alignment and the instructions for Class 2 Studio everything else seems ok.

## Possible Issues:
1. On the Module Home page the dates are still TBD but are up on the Calendar. https://github.com/LaunchCodeEducation/cs50x-live/tree/feature/module3/calendar/cs50/unit1-fundamentals/module3#steps
2. On the Calendar, Modules 1 and 2 are hyperlinks, but Module 3 is not. - https://github.com/LaunchCodeEducation/cs50x-live/tree/feature/module3/calendar#unit-1-fundamentals
3. Issue #146 is open (minor)  

## Some of the Changes:
1. Updated links to House of Tires on Prep for Class 1 schedule - https://github.com/LaunchCodeEducation/cs50x-live/commit/76c5554b8a3ef7b0fccdb57d3eef46e865bee5e7.
2. Spelling fix - https://github.com/LaunchCodeEducation/cs50x-live/commit/10ddbc608340800a735893ae6eb34efdbf1c25cd
3. Updated instructions for Sigma Breakdown Resource in class 2 prep - https://github.com/LaunchCodeEducation/cs50x-live/commit/0595ce8181b98a7374650462a630f60805dbc6a9
4. Fixed the quotes for algorithmic-efficiency quiz (Somehow the quotes show up funny and when it is copied to the IDE, it gives an error) - https://github.com/LaunchCodeEducation/cs50x-live/commit/e4994c9bc8e9095697891ab99ca4ac97fffb8da8
5. There were a couple more, but small fixes, you can take a look at them here - https://github.com/LaunchCodeEducation/cs50x-live/commits/feature/module3/calendar/cs50/unit1-fundamentals/module3

**Comment by jesseilev** [comment]
awesome
