### ISSUE TITLE
Pseudocode for functions follow along

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#143]
In the pseudocode for the functions-1 follow along, we say that it's a continuation of the previous program, but for the most part it's pretty different. functions-0 was a program saying "hello, name" and this is a function that ensures the user is giving us a positive int.

maybe want new pseudocode for this.

**Comment by newjoiner** [comment]
@stlou Thanks! I just provided some pseudocode for it.
