### ISSUE TITLE
bug in exercise: census

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#144]
I think there's a bug in this exercise.

At the bottom of census-1.c, in the promptAndValidate function, the printf function takes the argument of "answer", but I believe we want it to take the argument "fieldname" since we are trying to put in the string of the field.

I think leaving the bug in will confuse people more, rather than challenging them to find the bug and fix it.

**Comment by jesseilev** [comment]
nice, fixed
