### ISSUE TITLE
Exercise: Module 3, class 1 prep / Searching Algorithms

### ISSUE THREAD

**Issue by newjoiner** [LaunchCodeEducation/cs50x-live#146]
The third question in the quiz gives answers but not to the first part of the question. Not sure if this was done on purpose.  Also the given array has an even amount of numbers, the examples in Doug's Playlist and the Short have used an odd set of numbers.

> ### Question 3:
> 
> Given the following array:
> 
> {4, 7, 13, 18, 21, 42}
> 
> carry out the process of using binary search for the number ’21'.  For each iteration of binary search, show:
> 1.  which elements of the array are between the “start” and “end” elements
> 2.  which element is the “middle” element; highlight it by putting it between square brackets (i.e., put it between [])
> 3.  next to the final iteration, write “final iteration"
> 
> For example, let's say we did this question with the following array: 
> 
> {-6, 0, 1, 2, 3, 15, 20}
> 
> searching for the number '0'.
> 
> `A correct answer would look like this:`
> 
> `{-6, 0, 1, [2], 3, 15, 20}`
> 
> `{-6, [0], 1} final iteration`

**Comment by jesseilev** [comment]
I think it's ok.

The first part is basically just saying that the set of numbers should shrink. 

The even / odd difference shouldn't matter
