### ISSUE TITLE
More on for-loops resource typo

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#154]
There's a small typo in this resource: http://education.launchcode.org/cs50x-stlouis/calendar/cs50/unit1-fundamentals/module2/materials/resources/more-forloops/

This sentence: This explanation probably makes sense in a vague way, but nevertheless, you might still feel a little hazy on the details, because even normal for-loop syntax is very dense and cryptic, and when you saw the two variables declared, if youre like me, you said "Wait, what is this? That looks wrong. Can you do that?

Should be "you're" instead of "youre". Also, the sentence is a little whack, but maybe that's what we wanted.

**Comment by jesseilev** [comment]
improved this sentence and a few other things
