### ISSUE TITLE
Organization: Module 4 / Home page

### ISSUE THREAD

**Issue by newjoiner** [LaunchCodeEducation/cs50x-live#157]
@jesseilev 

Resources are still listed in Module 4 readme.

**Comment by stlou** [comment]
Ya I'm actually looking at this right now. Lot's of organization stuff to be done. I'm going to go through and just do some basic formatting to save you time, but we still need a Module 4 description, possibly still some studios, and the Problem Set 4 page needs to be finalized

**Comment by newjoiner** [comment]
Thanks, just made a couple of changes on pset 4 you can check here for those changes
https://github.com/LaunchCodeEducation/cs50x-live/issues/17

Studios: Word Stretch Grid got updated and ASCII Art didn't

**Comment by jesseilev** [comment]
Home page is done. 

Other features listed here have separate issues
