### ISSUE TITLE
exercise: CLC

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#173]
in command line calc: http://education.launchcode.org/cs50x-stlouis/calendar/cs50/unit1-fundamentals/module2/materials/exercises/command-line-calculator/

In the example of how the code should look, you have the user input two floats, and have the successful sum. People are going to have to use "atof" instead of "atoi" (i think), but we haven't told them about that function. They could look it up, but I think that's asking too much. Should probably just give it to them.

**Comment by jesseilev** [comment]
@stlou Looking at this again, this exercise seems pointless because of how similar it is to Previous. The only differences are trivial:
- you add two args together instead of subtracting `1` from one arg
- the args are `float`s instead of `int`s

Do you think we should just combine them into one?

**Comment by jesseilev** [comment]
I guess they're also different in that Previous is already mostly given to them, whereas this one they have to make the whole thing from scratch.

So let's keep them both

**Comment by jesseilev** [comment]
I added an explanation of `atof`
