### ISSUE TITLE
exercise: Algorithmic Efficiency quiz

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#192]
would be nice to give them solutions so they know if they answered it correctly

http://education.launchcode.org/cs50x-stlouis/calendar/cs50/unit1-fundamentals/module3/materials/exercises/algorithmic-efficiency/

**Comment by jesseilev** [comment]
@stlou I just noticed all these m3 issues. 

For QA stuff that needs to be done asap, add it to the Do Now milestone

**Comment by ghost** [comment]
I've created an answer key and committed it.
