### ISSUE TITLE
exercise: delmar house of tires

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#196]
Student issue re: makefile: https://piazza.com/class/ii659v08kpv73u?cid=158

Is this because the makefile we provide (http://education.launchcode.org/cs50x-stlouis/calendar/cs50/unit1-fundamentals/module3/materials/exercises/house-of-tires/makefile.html) has "all" only for 'pizza' and 'tires', instead of 'houseofpizza' and 'houseoftires'?

I'm a little confused because it seems to be working for my IDE. Can't tell if the student is messed up or if we need to change the makefile.

**Comment by jesseilev** [comment]
Ach, there was a problem after all. Two actually:
1. The Makefile `all` command still listed its "subcommands" as `pizza` and `tires` even though we changed their names to `houseofpizza` and `houseoftires`
2. Inside `mathhelper.c`, the line that says `#include "mathHelper.h"` should not be camel case, but it is.

I fixed them and it should be good now.

We should announce during class tomorrow: Oops sorry, we messed this one up, don't worry if you couldn't get it to work. Feel free to try it again with the new starter code.

@digshake @stlou
