### ISSUE TITLE
exercise: pointer table

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#197]
should provide solutions to this

**Comment by jesseilev** [comment]
I've written up an <a href="https://github.com/LaunchCodeEducation/cs50x-live/blob/master/calendar/cs50/unit2-advanced-c/module4/materials/exercises/pointer-practice/answer.md" target="_blank">answer key</a>, but it's maybe a little wonk, I want check with you guys and see.

The second statement

``` c
z = *x + 2;
```

assigns a new value to `z`. That new value is 2 + "whatever exists in memory at the address pointed to by `x`". But `x` is not a pointer, `x` is the integer value of `9`. So we're going to address `0x9` and adding `2` to whatever we find there ...

Some of the subsequent answers get effected as well, if they depend on `z`

@digshake @stlou Did I do something wrong?

**Comment by stlou** [comment]
let's just change this so that it's *px for the second statement

**Comment by jesseilev** [comment]
I changed the answer key and the assignment.

Might still be good to have someone double check my answers
@stlou @digshake
