### ISSUE TITLE
Module 6: Pset 6 Alt

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/cs50x-live#207]
See <a href="https://github.com/LaunchCodeEducation/cs50x-live/blob/feature/module6/calendar/cs50/unit3-web/module6/materials/problem-set/pset6-alt/README.md" target="_blank">assignment page</a>

**Comment by jesseilev** [comment]
Thanks @sehqlr 

I'm thinking slack could be really cool. Do you think the following would be possible:

We create a slack channel for this assignment. Each student must make an HTML page containing a form, which, on submission, POSTs a comment to the channel.

The thing I'm a little hazy on what the authentication process would look like, or if it would even be possible. Do you have a sense for this?

**Comment by jesseilev** [comment]
Thanks again @sehqlr !

**Comment by sehqlr** [comment]
You are welcome, @jesseilev, even though you did all the work!
