### ISSUE TITLE
resource: html forms

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#210]
getting a 404 when trying to open the .html files through the course website:

http://education.launchcode.org/cs50x-stlouis/calendar/cs50/unit3-web/module6/materials/resources/html-forms/

**Comment by jesseilev** [comment]
Hmm yeah, looks like couscous actually deletes any additional html files we try to make. So annoying.

I guess let's just do the standard markdown workaround. I would have preferred to give them actual html here.

@digshake remind me tomorrow to ask you about this
