### ISSUE TITLE
exercise:

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#213]

**Comment by stlou** [comment]
When you click "kidbrother.php" it downloads a file, instead of opening to a new window

https://github.com/LaunchCodeEducation/cs50x-live/blob/feature/module7/calendar/cs50/unit3-web/module7/materials/exercises/annoying-kid-brother/README.md

**Comment by jesseilev** [comment]
Should be fixed (looks fixed on [cs50x-stlouis repo](https://github.com/LaunchCodeEducation/cs50x-stlouis/blob/gh-pages/calendar/cs50/unit3-web/module7/materials/exercises/annoying-kid-brother/index.html), still not working on [website](http://education.launchcode.org/cs50x-stlouis/calendar/cs50/unit3-web/module7/materials/exercises/annoying-kid-brother/) as of right now
