### ISSUE TITLE
Organization: Exercise "Back" buttons

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/cs50x-live#23]
<a href="https://github.com/stlou"><img src="https://avatars.githubusercontent.com/u/10931986?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [stlou](https://github.com/stlou)**
_Tuesday Dec 15, 2015 at 20:59 GMT_
_Originally opened as https://github.com/Launch-Code/cs50x-live-2016/issues/85_

---

When you go to an Exercise, you stay in the same window (we like that, since you're staying internal within the curriculum / website). 

BUT, when you click the back button ("Go back to Prep for Class #"), it takes you back to the top of the Prep Work page. This ends up being a little annoying, since you constantly have to scroll down to find where you left off.

We can make those "Back" buttons link to the header for the section the exercise is in. We should do that. Students will appreciate it (even if they don't know that it could be worse, they'll know).

**Comment by jesseilev** [comment]
<a href="https://github.com/jesseilev"><img src="https://avatars.githubusercontent.com/u/4194941?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jesseilev](https://github.com/jesseilev)**
_Thursday Jan 07, 2016 at 20:41 GMT_

---

What's the status of this?

**Comment by jesseilev** [comment]
<a href="https://github.com/newjoiner"><img src="https://avatars.githubusercontent.com/u/15893841?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [newjoiner](https://github.com/newjoiner)**
_Friday Jan 08, 2016 at 17:04 GMT_

---

Hey @jesseilev I can take care of these

**Comment by newjoiner** [comment]
@jesseilev All of the links were updated to go to the appropriate section.
