### ISSUE TITLE
Pset Guide: Module 2

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#29]
Some small typos, want to make sure this is cleaned up and in final form. A few small things I noticed:

Under "Command-line Arguments: A Quick Review" it starts off saying "if a user enters..." but there's no completion to that sentence (should be like, "if x, then y", or something). 

There's also a winky face under the Caeser header that's part of a parentheses but doesn't close the parens, sort of. It just looks kind of confusing. Not really important, but should probably fix so it is polished. 

There may be a few other things. Just worth a final scrubbing.

**Comment by jesseilev** [comment]
:wink:
