### ISSUE TITLE
Organization: Module 3 / Merge Sort

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/cs50x-live#34]
_From @newjoiner on January 8, 2016 16:54_

Might want to add Doug's Playlist to this section.  All of the other sorting algorithms have doug's playlist video.

You can find the video [here](https://www.youtube.com/watch?v=sWtYJv_YXbo&index=6&list=PLhQjrBD2T382Bh-sc1w74c4V6_G2byC-T) and put it in Module 3 Class 2 Prep [here](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/class2-prep#merge-sort)

_Copied from original issue: Launch-Code/cs50x-live-2016#142_

**Comment by jesseilev** [comment]
_From @newjoiner on January 8, 2016 17:35_

forgot to mention @jesseilev

**Comment by jesseilev** [comment]
Added the video. Good catch @newjoiner .

**Comment by newjoiner** [comment]
hey @jesseilev I didn't see it, but I added it [here](https://github.com/LaunchCodeEducation/cs50x-live/blob/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/class2-prep/README.md)

**Comment by jesseilev** [comment]
Ha oops I added it on the old repository.
