### ISSUE TITLE
Studio: Module 3 / Multiplication and Exponents

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/cs50x-live#35]
_From @newjoiner on January 7, 2016 22:7_

The instructions for [this](https://github.com/Launch-Code/cs50x-live-2016/tree/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/studios/multiplication-exponent) studio can be broken up into parts.

Check the wiki [here](https://github.com/Launch-Code/cs50x-live-2016/blob/feature/wiki-folder/helpful-resources/modules/module-3.md#class-2-studio-multiplication-and-exponents) to see it broken up.

_Copied from original issue: Launch-Code/cs50x-live-2016#141_

**Comment by jesseilev** [comment]
_From @newjoiner on January 8, 2016 17:35_

forgot to mention @jesseilev

**Comment by jesseilev** [comment]
@newjoiner Want to go ahead and make the changes you have in mind?

**Comment by jesseilev** [comment]
@digshake Any chance you could rewrite the <a href="https://github.com/LaunchCodeEducation/cs50x-live/blob/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/studios/multiplication-exponent/Makefile" target="_blank">Makefile</a> to use `clang` instead of `g++`? 

As a point of reference, for Pset3 they will be given <a href="http://cdn.cs50.net/2015/fall/psets/3/pset3/pset3/find/Makefile.src" target="_blank">this</a>. I don't think our example needs to be as complicated.

**Comment by newjoiner** [comment]
@jesseilev 
I broke the studio up into parts.

Makefile if you need:

all: expt

expt: expt.c mult.c mult.h
    clang -ggdb3 -O0 -std=c11 -Wall -Werror -o expt expt.c mult.c -lcs50 -lm

clean:
    rm -f *.o a.out core expt

**Comment by digshake** [comment]
Looks good to me!

**Comment by newjoiner** [comment]
@jesseilev The instructions for the make file still reference the old makefile.

https://github.com/LaunchCodeEducation/cs50x-live/tree/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/studios/multiplication-exponent

``` nohighlight
~/workspace $ make
g++ expt.c mult.c mult.h -o expt
g++: error: mult.c: No such file or directory
g++: error: mult.h: No such file or directory
```

> The first line attempts to make the program. The next line shows what the makefile is trying to do: compile a program that consists of three files, `mult.c`, `mult.h`, and `expt.c`. Unfortunately we are missing two of those files: `mult.c` and `mult.h`.

This is the result when the makefile and expt.c are copied over:

```
~/workspace $ make
make: *** No rule to make target `mult.c', needed by `expt'.  Stop.
```

We can reference them to the pset3 guide or give some similar explanation. 

http://cdn.cs50.net/2015/fall/psets/3/pset3/pset3.html

Let me know which direction you'd like to go in.  I can write something up and send it to you tomorrow if you would like an explanation there.

**Comment by jesseilev** [comment]
Thanks @newjoiner, yeah let's provide our own explanation. I'd rather not send them over to Pset3 during studio, because it's always messy to say "go and read this one tiny section of a very large document" 

(We can blatantly plagiarize the Pset explanation, if that's the best way to explain it, but don't explicitly refer to the problem set anywhere.)

**Comment by newjoiner** [comment]
@jesseilev check out the new instructions.  I also provided a link to the makefile wikipedia page, but you can take it out.  My explanation may be a little long, so you may want to trim it down.

https://github.com/LaunchCodeEducation/cs50x-live/blob/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/studios/multiplication-exponent/README.md
1. All of the links on the page end in *.html. If that's not correct let me know.
2. I updated the makefiles to make sure they had tabs in the correct places.
3. Also I had to update the pseudocode. I see you have helpful resources on the module 3 branch, but I updated it on the wiki-folder branch.

**Comment by stlou** [comment]
@jesseilev 
should we close this? i believe this is done
