### ISSUE TITLE
Exercise: Module 3, class 1 prep / Algorithmic Efficiency Quiz

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/cs50x-live#36]
_From @newjoiner on January 7, 2016 22:0_

The program for question 1 does not return the biggest number.  Does not have anything to do with the question, but just in case they copy the program over.
### Original Program

``` c
#include <cs50.h>
#include <stdio.h>

int main(void)
{
  // set up example data
  int exampleArray[] = {12, -2, 0, 15, 27, 20, 6};
  int exampleSize = 7;

  bool seenOne = false;
  int currentMax = 0;

  for (int i = 0; i < exampleSize; i++)
  {
    if (!seenOne){
      currentMax = exampleArray[i];
    } else if (exampleArray[i] > currentMax){
      currentMax = exampleArray[i];
    }
  }
  printf(“The biggest number was %i\n”, currentMax);
}
```
### Suggested Program

``` c
#include <cs50.h>
#include <stdio.h>

int main(void)
{

  // set up example data
  int exampleArray[] = {12, -2, 0, 15, 27, 20, 6};
  int exampleSize = 7;

  int currentMax = 0;

  for (int i = 0; i < exampleSize; i++)
  {
        if (exampleArray[i] > currentMax )
        {
             currentMax = exampleArray[i];
        } 

  }
  printf("The biggest number was %i\n", currentMax);
}

```

_Copied from original issue: Launch-Code/cs50x-live-2016#140_

**Comment by jesseilev** [comment]
_From @newjoiner on January 8, 2016 17:36_

forgot to mention @jesseilev

**Comment by jesseilev** [comment]
fixed!

@newjoiner Does this mean that in general you've been checking all our example code to make sure it works? If so, that would be a huge relief! I've been wondering how many buggy examples are out there..

**Comment by newjoiner** [comment]
I checked a couple that stood out, but I'll recheck.

**Comment by jesseilev** [comment]
Ok yeah, don't go out of your way, I was just curious
