### ISSUE TITLE
Exercise: Module 3, class 2 prep / Delmar House of Tires

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/cs50x-live#37]
_From @newjoiner on January 7, 2016 21:16_

In the exercise instructions students are told to include the mathHelper.h file, but it is already in the file.  We can comment that out and put a Todo like in <a href="https://github.com/Launch-Code/cs50x-live-2016/blob/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/exercises/spread-out/houseOfTires.c" target="_blank">houseOfTires.c</a>

_Instructions for Module 3_
3 Add a line to #include mathHelper.h in <a href="https://github.com/Launch-Code/cs50x-live-2016/blob/feature/module3/calendar/cs50/unit1-fundamentals/module3/materials/exercises/spread-out/houseOfPizza.c" target="_blank">houseOfPizza.c</a>

This is the first exercise where students will be handling multiple files on their own.  It might be good to add some instructions for compiling as well. In Studio Multiplication and Exponents they are given a make file.

_Copied from original issue: Launch-Code/cs50x-live-2016#139_

**Comment by jesseilev** [comment]
_From @newjoiner on January 8, 2016 17:36_

@jesseilev

**Comment by jesseilev** [comment]
@newjoiner Good point. I think we should just give them a Makefile.

**Comment by newjoiner** [comment]
This one works if you need it. (I did it in the style of pset 3)

```
all: pizza tires

pizza: houseOfPizza.c mathHelper.c mathHelper.h
    clang -ggdb3 -O0 -std=c11 -Wall -Werror -o houseOfPizza houseOfPizza.c mathHelper.c -lcs50 -lm

tires: houseOfTires.c mathHelper.c mathHelper.h
    clang -ggdb3 -O0 -std=c11 -Wall -Werror -o houseOfTires houseOfTires.c mathHelper.c -lcs50 -lm 

clean:
    rm -f *.o a.out core pizza tires 
```

**Comment by jesseilev** [comment]
! Awesome
