### ISSUE TITLE
GH Pages: Links to Markdown

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/cs50x-live#64]
Some links take us to the markdown page instead of the generated html page.

For example

http://education.launchcode.org/cs50x-stlouis/helpful-resources/Supplementary-Resources/c-language.md#precedence

should be

http://education.launchcode.org/cs50x-stlouis/helpful-resources/Supplementary-Resources/c-language.html#precedence 

This link came from <a href="http://education.launchcode.org/cs50x-stlouis/calendar/cs50/unit1-fundamentals/module1/materials/class1-prep#printing-getting-user-input#getting-set-up" target="_blank">Module 1 / Class 1 Prep</a> towards the bottom.

@digshake, I think I know the reason why this is happening, but I don't know how to fix it. The problem is that the original link points explicitly to a `.md` file, rather than to a folder with a README. Does that sound right? If so, I can thin of two possible solutions:
1. Add a patch to the couscous script. Do you think this would be an easy fix or a difficult one?
2. Reorganize the `helpful-resources` folder so that we only have README.md files, and change all our links so that they point to those folders.

**Comment by stlou** [comment]
Just making a note: also happens for the "string replacement cheatsheet" in prep for class 1

**Comment by digshake** [comment]
I think this is a symptom of inconsistency when creating README.md files. Links should _always_ go to the folder, never directly to the markdown file. We will need to go through and correct this when we get a chance, and make sure people know to be careful of this in the future.

**Comment by digshake** [comment]
Fixed all the existing links. We should make sure to link to html pages instead of markdown pages from now on.

**Comment by jesseilev** [comment]
awsome!
