### ISSUE TITLE
GH Pages: Code Snippets

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/cs50x-live#67]
Often the formatting is all wonky inside code snippets. For example, see the Marathon exercise, where random words are bolded.

http://education.launchcode.org/cs50x-stlouis/calendar/cs50/unit1-fundamentals/module1/materials/exercises/marathon/

**Comment by stlou** [comment]
Another weird example of this is in the "book" exercise, where random words are in red (and there's random bolding): http://education.launchcode.org/cs50x-stlouis/calendar/cs50/unit1-fundamentals/module1/materials/exercises/book/

**Comment by stlou** [comment]
Also, there's a weirdly different-colored "code box" in the How Many Oranges exercise:

http://education.launchcode.org/cs50x-stlouis/calendar/cs50/unit1-fundamentals/module1/materials/exercises/oranges/

**Comment by digshake** [comment]
The different colored box was me experimenting to try and find a solution.

The solution that I found is that all code blocks need to be annotated with the language that they represent. So all code blocks for c code should be:

```c

For command line blocks we don't want syntax highlighting so the following should be used:

```nohighlight

These will have to be changed for everything that has been done so far, and we need to make sure to label things properly for all future exercises that are created.

**Comment by digshake** [comment]
I've fixed all the code snippets, they just need to be pushed to the website. Can you take care of this @jesseilev ?

**Comment by jesseilev** [comment]
done!

**Comment by jesseilev** [comment]
From now on, let's only create markdown files

**Comment by stlou** [comment]
there is one snippet that is not fixed in the "Dollars and Cents" studio. Not super important, but for consistency would be good to switch it over. 

http://education.launchcode.org/cs50x-stlouis/calendar/cs50/unit1-fundamentals/module1/materials/studios/dollars-and-cents/

**Comment by digshake** [comment]
Looks correct to me. There's one block of C code and one block of command line code on that page, so they should look different.
