### ISSUE TITLE
GH pages: "Helpful Resources"

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#69]
very small detail, but in the "helpful resources" we keep referring to it as a wiki, but it's not really functioning that way. Might just want to call them helpful resources...

**Comment by stlou** [comment]
just making a note: it is also referred to as "cs50x wiki" in the "hello" exercise.

**Comment by newjoiner** [comment]
> very small detail, but in the "helpful resources" we keep referring to it as a wiki, but it's not really functioning that way. Might just want to call them helpful resources...

just changed it on the `feature/wiki-folder` branch

>  just making a note: it is also referred to as "cs50x wiki" in the "hello" exercise.

just changed it on the `feature/module1` branch

@jesseilev

**Comment by newjoiner** [comment]
@jesseilev BTW I changed all of the places where "wiki" was mentioned on their respective branches.

On the "Home Page", where it talked about the wiki on the bottom of the page, I changed it on the `feature/module1` branch

**Comment by digshake** [comment]
I just checked the page and found no more references to a wiki, so I'm closing this.
