### ISSUE TITLE
.c files 

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#71]
Jesse is aware of this, but any of the .c files come out in raw text, with no highlighting / formatting. Need to decide what we want to do here... maybe we put them in the blocks of code, like in other READMEs. But might look weird if that's all that's on the page. 

Good example is in Marathon: http://education.launchcode.org/cs50x-stlouis/calendar/cs50/unit1-fundamentals/module1/materials/exercises/marathon/marathon.c

**Comment by jesseilev** [comment]
Next week we should be able to knock out a script that converts all our .c files to markdown.

Afterwards, we should also potentially put the master branch back on the st louis fork

**Comment by digshake** [comment]
I've converted all the c files into markdown, it just needs to be pushed to the website. Can you take care of this @jesseilev ?

**Comment by jesseilev** [comment]
Awesome, it's up.

Are these automatically converted, or did you have to make them by hand?

**Comment by jesseilev** [comment]
One strange thing:

The [oranges](http://education.launchcode.org/cs50x-stlouis/calendar/cs50/unit1-fundamentals/module1/materials/exercises/oranges/) exercise still looks weird for _one_ of the code blocks, but not the other.

They're both [annotated](https://github.com/LaunchCodeEducation/cs50x-live/blob/master/calendar/cs50/unit1-fundamentals/module1/materials/exercises/oranges/README.md) with `nohighlight` ...

**Comment by jesseilev** [comment]
This is basically fixed. I made a separate issue #112 for the Oranges thing
