### ISSUE TITLE
Exercise: Module 2, class 2 prep / Previous

### ISSUE THREAD

**Issue by newjoiner** [LaunchCodeEducation/cs50x-live#72]
@jesseilev  In the [exercise](https://github.com/LaunchCodeEducation/cs50x-live/tree/feature/module2/calendar/cs50/unit1-fundamentals/module2/materials/exercises/previous) it says that atoi can be found in the `string.h library`, but it's in the `stdlib.h` library. Check CS50 <a href="https://cs50.harvard.edu/resources/cppreference.com/stdstring/atoi.html" target="_blank"> C Reference</a>

There's no need to include that library. (BTW the file `previous.c` does not include it)

> The `<string.h>` library is where atoi is defined, so don't forget to include it at the top of the file.`

**Comment by jesseilev** [comment]
Good catch @newjoiner. I removed the line telling them to include the library. 

I also realized that I forgot to add `argc` and `argv` to the signature of `main()`, so I added those
