### ISSUE TITLE
GH pages: sidebar

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#74]
The links on the sidebar don't link out to new tabs. I think they probably should. Let's make that happen!

**Comment by stlou** [comment]
also, maybe include the slack channel? not sure if we need to, but there's a cs50 slack channel that some stl mentors made, maybe a helpful resource for people

**Comment by stlou** [comment]
also, need to change piazza so it doesn't require wustl login

**Comment by digshake** [comment]
I've tried fixing the links but it is being very stubborn. I'm sure there's a way to do it but I can't figure it out right now.

Adding the slack link would be easy, but I don't have it.

For Piazza, see #76
