### ISSUE TITLE
Exercise: How Many Oranges

### ISSUE THREAD

**Issue by stlou** [LaunchCodeEducation/cs50x-live#77]
I may be wrong about this, but in the "How Many Oranges" exercise, we make it seem like we want the people to return with an "int" of how many oranges we want. While this is strictly true, if you try to do this using an `int` data type, you will probably get the wrong answer. Really, we need people to be using `float`. You could cast your float back as an int, but since we haven't talked about that, we wouldn't really expect people to be able to do that.

As it is, I would suggest adding in something along the lines of "Hint: it's ok to return the number of oranges as a float".

**Comment by jesseilev** [comment]
I fixed the casting problem.
